---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-agent
  labels:
    app: ops-agent
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-agent
  template:
    metadata:
      labels:
        app: ops-agent
        version: v1
    spec:
      serviceAccountName: ops-agent
      containers:
      - name: ops-agent
        image: quay.io/rbrhssa/ops-agents:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2024
          name: http
          protocol: TCP
        env:
        # LLM Configuration (override config.yaml)
        - name: LLM_BASE_URL
          valueFrom:
            secretKeyRef:
              name: ops-agent-secrets
              key: llm-base-url
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: ops-agent-secrets
              key: llm-api-key
        - name: LLM_DEFAULT_MODEL
          valueFrom:
            configMapKeyRef:
              name: ops-agent-config
              key: llm-model
        - name: LLM_TEMPERATURE
          value: "0.0"
        - name: LLM_MAX_TOKENS
          value: "1200"
        
        # Ansible Configuration
        - name: ANSIBLE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ops-agent-config
              key: ansible-api-url
        
        # Agent Configuration
        - name: AGENT_NAME
          value: "OpsAgent"
        - name: DEBUG
          value: "false"
        - name: PYTHONPATH
          value: "/opt/app-root/src/ops-agent"
        
        # Resource requests and limits
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /ok
            port: 2024
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /ok
            port: 2024
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        # Startup probe (for slow startups)
        startupProbe:
          httpGet:
            path: /ok
            port: 2024
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 12
        
        # Volume mounts
        volumeMounts:
        - name: config
          mountPath: /opt/app-root/src/ops-agent/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: data
          mountPath: /opt/app-root/src/ops-agent/data
      
      # Volumes
      volumes:
      - name: config
        configMap:
          name: ops-agent-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: data
        emptyDir: {}
      
      # Security context for OpenShift
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: ops-agent
  labels:
    app: ops-agent
spec:
  selector:
    app: ops-agent
  ports:
  - name: http
    port: 2024
    targetPort: 2024
    protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ops-agent
  labels:
    app: ops-agent
spec:
  to:
    kind: Service
    name: ops-agent
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-agent
  labels:
    app: ops-agent
